//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Resources.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be greater than the current date!.
        /// </summary>
        public static string Error_BOfDateNotGreatNow {
            get {
                return ResourceManager.GetString("Error_BOfDateNotGreatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data failed!.
        /// </summary>
        public static string Error_Create {
            get {
                return ResourceManager.GetString("Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting data failed!.
        /// </summary>
        public static string Error_Delete {
            get {
                return ResourceManager.GetString("Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department code already exists!.
        /// </summary>
        public static string Error_DepartmentCodeDuplicated {
            get {
                return ResourceManager.GetString("Error_DepartmentCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department code cannot be left blank!.
        /// </summary>
        public static string Error_DepartmentCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepartmentCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name cannot be left blank!.
        /// </summary>
        public static string Error_DepartmentNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepartmentNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department names are not allowed to have numbers!.
        /// </summary>
        public static string Error_DepartmentNameNotNumber {
            get {
                return ResourceManager.GetString("Error_DepartmentNameNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data failed!.
        /// </summary>
        public static string Error_Edit {
            get {
                return ResourceManager.GetString("Error_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses cannot be left blank!.
        /// </summary>
        public static string Error_EmailNotEmpty {
            get {
                return ResourceManager.GetString("Error_EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code already exists!.
        /// </summary>
        public static string Error_EmployeeCodeDuplicated {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code cannot be left blank!.
        /// </summary>
        public static string Error_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee names are not allowed to have numbers!.
        /// </summary>
        public static string Error_EmployeeNameNotNumber {
            get {
                return ResourceManager.GetString("Error_EmployeeNameNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please contact MISA for help!.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee names cannot be left blank!.
        /// </summary>
        public static string Error_FullNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_FullNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue date cannot be greater than the current date!.
        /// </summary>
        public static string Error_IdentityDateNotGreatNow {
            get {
                return ResourceManager.GetString("Error_IdentityDateNotGreatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card cannot be left blank!.
        /// </summary>
        public static string Error_IdentityNumberNotEmpty {
            get {
                return ResourceManager.GetString("Error_IdentityNumberNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card is not allowed to have letters!.
        /// </summary>
        public static string Error_IdentityNumberNotLetter {
            get {
                return ResourceManager.GetString("Error_IdentityNumberNotLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data does not exist!.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers cannot be left blank!.
        /// </summary>
        public static string Error_PhoneNumberNotEmpty {
            get {
                return ResourceManager.GetString("Error_PhoneNumberNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers are not allowed to have letters!.
        /// </summary>
        public static string Error_PhoneNumberNotLetter {
            get {
                return ResourceManager.GetString("Error_PhoneNumberNotLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position code already exists!.
        /// </summary>
        public static string Error_PositionCodeDuplicated {
            get {
                return ResourceManager.GetString("Error_PositionCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position codes cannot be left blank!.
        /// </summary>
        public static string Error_PositionCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_PositionCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position names cannot be left blank!.
        /// </summary>
        public static string Error_PositionNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_PositionNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position names cannot contain numbers!.
        /// </summary>
        public static string Error_PositionNameNotNumber {
            get {
                return ResourceManager.GetString("Error_PositionNameNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input!.
        /// </summary>
        public static string Error_ValidData {
            get {
                return ResourceManager.GetString("Error_ValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not in the correct format, please re-enter!.
        /// </summary>
        public static string Error_ValidEmail {
            get {
                return ResourceManager.GetString("Error_ValidEmail", resourceCulture);
            }
        }
    }
}
