//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được phép lớn hơn ngày hiện tại!.
        /// </summary>
        public static string Error_BOfDateNotGreatNow {
            get {
                return ResourceManager.GetString("Error_BOfDateNotGreatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công!.
        /// </summary>
        public static string Error_Create {
            get {
                return ResourceManager.GetString("Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công!.
        /// </summary>
        public static string Error_Delete {
            get {
                return ResourceManager.GetString("Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu không thành công!.
        /// </summary>
        public static string Error_Edit {
            get {
                return ResourceManager.GetString("Error_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không được phép để trống!.
        /// </summary>
        public static string Error_EmailNotEmpty {
            get {
                return ResourceManager.GetString("Error_EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại!.
        /// </summary>
        public static string Error_EmployeeCodeDuplicated {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống!.
        /// </summary>
        public static string Error_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên nhân viên không được phép có số!.
        /// </summary>
        public static string Error_EmployeeNameNotNumber {
            get {
                return ResourceManager.GetString("Error_EmployeeNameNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được trợ giúp!.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên nhân viên  không được phép để trống!.
        /// </summary>
        public static string Error_FullNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_FullNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được phép lớn hơn ngày hiện tại!.
        /// </summary>
        public static string Error_IdentityDateNotGreatNow {
            get {
                return ResourceManager.GetString("Error_IdentityDateNotGreatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND, CCCD không được phép có chữ!.
        /// </summary>
        public static string Error_IdentityNumberNotDigit {
            get {
                return ResourceManager.GetString("Error_IdentityNumberNotDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMTND, CCCD không được phép để trống!.
        /// </summary>
        public static string Error_IdentityNumberNotEmpty {
            get {
                return ResourceManager.GetString("Error_IdentityNumberNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại!.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép có chữ!.
        /// </summary>
        public static string Error_PhoneNumberNotDigit {
            get {
                return ResourceManager.GetString("Error_PhoneNumberNotDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép để trống!.
        /// </summary>
        public static string Error_PhoneNumberNotEmpty {
            get {
                return ResourceManager.GetString("Error_PhoneNumberNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí đã tồn tại!.
        /// </summary>
        public static string Error_PositionCodeDuplicated {
            get {
                return ResourceManager.GetString("Error_PositionCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được phép để trống!.
        /// </summary>
        public static string Error_PositionCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_PositionCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí không được phép để trống!.
        /// </summary>
        public static string Error_PositionNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_PositionNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí không được phép có số!.
        /// </summary>
        public static string Error_PositionNameNotNumber {
            get {
                return ResourceManager.GetString("Error_PositionNameNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ!.
        /// </summary>
        public static string Error_ValidData {
            get {
                return ResourceManager.GetString("Error_ValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng, vui lòng nhập lại!.
        /// </summary>
        public static string Error_ValidEmail {
            get {
                return ResourceManager.GetString("Error_ValidEmail", resourceCulture);
            }
        }
    }
}
